### ISSUE TITLE
KeyError on battery_service.py

### ISSUE THREAD

**Issue by Micha854** [pulquero/BatteryAggregator#1]
Hey,

when frech installed BatteryAggregator starting success!
the log says:
`@400000006422214c2fc74ce4 BatteryAggregator/setup: adding BatteryAggregator/setup to reinstallScriptsList
@400000006422214c32f883ec BatteryAggregator/setup: completed
@400000006422214d2da733d4 INFO:root:registered ourselves on D-Bus as com.victronenergy.battery.aggregator
@400000006422214d2f163cc4 INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
@400000006422214d2f41a9f4 INFO:dbusmonitor:Found: com.victronenergy.battery.socketcan_can8, scanning and storing items
@400000006422214d2f71418c INFO:dbusmonitor:       com.victronenergy.battery.socketcan_can8 has device instance 512
@400000006422214d30430c94 INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
@400000006422214d305947fc INFO:battery:Registered Battery Aggregator`

than restarting my raspberry Pi and check the log file:
`@40000000642221a53a38f204 *** CCGX booted (0) ***
@40000000642221a937496394 INFO:root:registered ourselves on D-Bus as com.victronenergy.battery.aggregator
@40000000642221a93a27a83c INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
@40000000642221a93a59957c INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
@40000000642221a93a728834 INFO:battery:Registered Battery Aggregator
@40000000642221aa0df543dc Traceback (most recent call last):
@40000000642221aa0df55f34   File "/data/BatteryAggregator/battery_service.py", line 217, in publish
@40000000642221aa0df572bc     self.update()
@40000000642221aa0df57a8c   File "/data/BatteryAggregator/battery_service.py", line 213, in update
@40000000642221aa0df58a2c     self._local_values[alarm] = aggregated_alarms[alarm]
@40000000642221aa0df599cc KeyError: '/Alarms/CellImbalance'
@40000000642221bd06ab92ac INFO:dbusmonitor:Found: com.victronenergy.battery.socketcan_can8, scanning and storing items
@40000000642221bd0768241c INFO:dbusmonitor:       com.victronenergy.battery.socketcan_can8 has device instance 512`

what is the problem? ich have connected my pylontech with can-hat on waveshare

**Comment by pulquero** [comment]
Fixed and pushed v1.3.
