### ISSUE TITLE
Victron Shunt always added to BatteryAggregator

### ISSUE THREAD

**Issue by SlapJackNpNp** [pulquero/BatteryAggregator#11]
Hello,

first of all, thanks for this tool!

I just set it up with two dalys but i always have the victron smartshunts added to the battery aggregation. My config looks like this: 

{
	"excludedServices": ["com.victronenergy.battery.shunt1"]
}
{
	"virtualBatteries": ["com.victronenergy.battery.virtual1": ["com.victronenergy.battery.shunt1", "com.victronenergy.battery.leastPrecedence"]]
}

i tried removing the batteryshunt from the virtualbatteries entry aswell but to no succes. Not sure what i'm doing wrong.

Thank you for your help. 
![config](https://github.com/pulquero/BatteryAggregator/assets/26175386/be44ca35-d9d6-4660-8630-b24d24b7cc49)

**Comment by pulquero** [comment]
Services mentioned in virtualBatteries are automatically excluded. What are the service names of all your devices (or please attach a screen shot of dbus-spy)?

**Comment by SlapJackNpNp** [comment]
What exactly is dbus-spy. Do you mean the list of devices shown in the cerbo? Or ist it a command i can execute over ssh?

**Comment by pulquero** [comment]
Command over ssh.

**Comment by SlapJackNpNp** [comment]
![image](https://github.com/pulquero/BatteryAggregator/assets/26175386/be861fb4-b39a-4286-b478-dd90bcd4433f)
This is what i get with dbus-spy i hope this helps?

**Comment by pulquero** [comment]
You want something like this (I may have the shunts the wrong way round)
```
	{
		"virtualBatteries": {
			"com.victronenergy.battery.virtual1": ["com.victronenergy.battery.ttyS6", "com.victronenergy.battery.ttyUSB0"],
			"com.victronenergy.battery.virtual2": ["com.victronenergy.battery.ttyS7", "com.victronenergy.battery.ttyUSB2"]
		}
	}
```

**Comment by SlapJackNpNp** [comment]
So what exactly will this do? Like my goal is to ignore the smart shunts for the aggregator and only use the dalys. Atm i have 2 packs, each with 1 daly and 1 smart shunt. I want ti get the data and the control from the dalys and use the shunts only to check the consumptions while i monitor the system. 

Currently the aggregator uses all 4 so i get each current twice. 

So yeah how can i get the aggregator to ignore the shunts and only use the dalys? 

Thank you very much

**Comment by pulquero** [comment]
This will combine a shunt with a daly to form a virtual battery - it will take the consumption from the shunt, and fill in any other parameters from the daly so you have the merged combination of the two. So, you'll have a virtual battery for each pack. And the aggregator will just aggregate these two virtual batteries.

    Aggregator ---- Virt Batt 1 ---- Shunt
                                ---- Daly
                                           
               ---- Virt Batt 2 ---- Shunt
                                ---- Daly

**Comment by SlapJackNpNp** [comment]
Oooh that sounds amazing. Gonna test that tomorrow. Thank you very much!

**Comment by SlapJackNpNp** [comment]
Okay, so i added the command you suggested: 

{
"virtualBatteries": {
"com.victronenergy.battery.virtual1": ["com.victronenergy.battery.ttyS7", "com.victronenergy.battery.ttyUSB2"],
"com.victronenergy.battery.virtual2": ["com.victronenergy.battery.ttyS6", "com.victronenergy.battery.ttyUSB0"]
}
}

I sorted it, so that the BMS and the shunt fit together. That is the only command i hace in the config.json atm. 
![Aggreagtor](https://github.com/pulquero/BatteryAggregator/assets/26175386/3151fc58-ad8b-4adc-88c6-ea461b4d44d9)
The Aggregator still uses 3 Units somehow tho, meaning that the showed values are not correct. Unfortunately i don't know what the 3rd unit is the aggregator is using. 

This is what the dbus-spy shows. 
![Dbus-spy](https://github.com/pulquero/BatteryAggregator/assets/26175386/9cef3395-5391-4aca-b00d-15a92eb22dbe)

Is there btw a way to name the Virtaul Batteries somehow? 

Thank you very much again for the help!

**Comment by Marccatamaran** [comment]
Hi,
almost the same isssue, can't succed to exclud my shunt from the equation ? I create the file config.json with nano in the folder specified and try many way to try to exclud my shunt, but no cigar! 

I would like to see only my two Daly Bms the Battery Aggregator.
please advise


Services
com.victronenergy.adc
com.victronenergy.battery.aggregator                                                                                                                                       Battery Aggregator
com.victronenergy.battery.ttyS5                                                                                                                                          SmartShunt 500A/50mV
com.victronenergy.battery.ttyUSB0                                                                                                                                         SerialBattery(Daly)
com.victronenergy.battery.ttyUSB1                                                                                                                                         SerialBattery(Daly)
com.victronenergy.ble
com.victronenergy.digitalinput.input01                                                                                                                                      Haut niveau d eau
com.victronenergy.digitalinput.input02                                                                                                                                          Bilge pump on
com.victronenergy.fronius
com.victronenergy.logger
com.victronenergy.modbusclient.tcp
com.victronenergy.packageManager                                                                                                                                              Package Manager
com.victronenergy.platform
com.victronenergy.qwacs
com.victronenergy.settings
com.victronenergy.solarcharger.ttyS6                                                                                                                           SmartSolar Charger MPPT 100/50
com.victronenergy.system
com.victronenergy.tank.adc_builtin0_1                                                                                                                                      Generic Tank Input
com.victronenergy.tank.adc_builtin0_2                                                                                                                                      Generic Tank Input
com.victronenergy.tank.adc_builtin0_3                                                                                                                                      Generic Tank Input
com.victronenergy.tank.adc_builtin0_4                                                                                                                                      Generic Tank Input
com.victronenergy.temperature.adc_builtin0_7                                                                                                                        Generic Temperature Input
com.victronenergy.temperature.adc_builtin0_8                                                                                                                        Generic Temperature Input
com.victronenergy.temperature.ruuvi_d6d9450a143f                                                                                                                                     RuuviTag
com.victronenergy.temperature.ruuvi_d76471a7ef46                                                                                                                                     RuuviTag
com.victronenergy.temperature.ruuvi_e49b90c9f9b4                                                                                                                                     RuuviTag
com.victronenergy.temperature.ruuvi_f616a54e79c2                                                                                                                                     RuuviTag
com.victronenergy.vebus.ttyS4                                                                                                                                   MultiPlus 12/3000/120-50 120V

**Comment by pulquero** [comment]
@Marccatamaran  So you have one shunt across both batteries? So are you looking to aggregate the two Dalys and then have the result merged with the shunt?

**Comment by Marccatamaran** [comment]
Yes I have my two Daly BMS on 560ah each  and after I have my victron
shunt! This one totalise whatever I take from the two Daly BMS!

At the end it would good if I drive my voltage with the Battery aggregator
and use the SOC from the victron shunt!
The Daly BMS have a tendency to drift on the SOC.

Right now if I charge with 100 amps
Each Daly show 50  amps that shut show 100  amps and the batteraggregetor
show 200 amps.

**Comment by pulquero** [comment]
Currently this is not possible, but I'll see if I can make some changes to allow it.

**Comment by Marccatamaran** [comment]
Can you show how to remove the victron shunt from the equation of the Batteryaggragator?

**Comment by pulquero** [comment]
Yes, for now you can add
"excludedServices": ["com.victronenergy.battery.shunt1"],

**Comment by Marccatamaran** [comment]
Hi,
I created the file using nano and paste the "excludedServices": ["com.victronenergy.battery.shunt1"], and reboot the Cerbo GX Still have 3 Battery ?

![Capture d’écran 2023-11-23 085647](https://github.com/pulquero/BatteryAggregator/assets/122734078/0e5b390d-631c-4b82-82ec-6be67697d270)


![Capture d’écran 2023-11-23 091116](https://github.com/pulquero/BatteryAggregator/assets/122734078/d8325d18-3d46-4b3d-823f-2a4734d4acc3)



![Capture d’écran 2023-11-23 090154](https://github.com/pulquero/BatteryAggregator/assets/122734078/7113c562-586a-494e-a2d3-4a340a37163e)
![Capture d’écran 2023-11-23 090258](https://github.com/pulquero/BatteryAggregator/assets/122734078/f69b5acc-eaa3-4750-9a05-3f0a0c9ac73e)

What I do wrong?
Thanks in advance for your support!





































                                                                                       [ Read 1 line ]
^G Get Help      ^O Write Out     ^W Where Is      ^K Cut Text      ^J Justify       ^C Cur Pos       M-U Undo         M-A Mark Text    M-] To Bracket   M-Q Previous     ^B Back
^X Exit          ^R Read File     ^\ Replace       ^U Paste Text    ^T To Spell      ^_ Go To Line    M-E Redo         M-6 Copy Text    ^Q Where Was     M-W Next         ^F Forward

**Comment by pulquero** [comment]
If you don't have an existing file then the full contents should be:
``
{
"excludedServices": ["com.victronenergy.battery.shunt1"]
}
``
See (updated) examples here: https://github.com/pulquero/BatteryAggregator

**Comment by pulquero** [comment]
Ok, it's here, version 2.2. It is now possible to merge shunt data with aggregated data, example config:

### Aggregate all available batteries with additional info provided by a shunt

	{
		"auxiliaryServices": ["com.victronenergy.battery.shunt1"]
	}
