### ISSUE TITLE
Aggregator Current issue

### ISSUE THREAD

**Issue by nik-bok** [pulquero/BatteryAggregator#12]
Hi,

Would you be so kind to check why my aggregator is showing far more amps then two my battery banks or shunt?
On the other hand, Lynx Shunt current is very close almost 100% correct if adding Batt1 and Batt2.
I have two JK BMSes, btw.

![Screenshot 2023-11-01 at 14 07 21](https://github.com/pulquero/BatteryAggregator/assets/149593321/22ca15e3-de8c-4406-9255-bdcc9439c18e)
![Screenshot 2023-11-01 at 13 46 42](https://github.com/pulquero/BatteryAggregator/assets/149593321/a7746a0f-bc21-49b1-a8c0-4a24fee42a98)

For some reason in the Aggregator/System it shows 3 batteries.
![Screenshot 2023-11-01 at 14 30 56](https://github.com/pulquero/BatteryAggregator/assets/149593321/fdcfe1ec-79c3-4457-88ef-ed347a00ad4b)

and...

![Screenshot 2023-11-01 at 14 32 12](https://github.com/pulquero/BatteryAggregator/assets/149593321/9530fd62-bf47-4859-ba82-0865c1c05002)

**Comment by pulquero** [comment]
If you look at /System/Batteries under the aggregator in dbus-spy it should list which 3 services it is aggregating.

**Comment by pulquero** [comment]
Closing as no further response received.
