### ISSUE TITLE
Clearer description for excluding services

### ISSUE THREAD

**Issue by Albarge** [pulquero/BatteryAggregator#14]
Hi, Thanks for the Battery Aggregator.

I had trouble figuring out how the excluded services works in the config.json, then finally cracked it after reading through old issues, as it wasn't obvious to me from the initial read me note.

Can I suggest it would also help others if a bit more info was added in the read me, something like:

To exclude the battery service com.victronenergy.battery.shunt1, first run dbus-spy from command line to see the address for the shunt you wish to exclude,  it will show up as: com.victronenergy.battery.tty7 or similar, so add:

	"excludedServices": ["com.victronenergy.battery.shunt1"]

But replace shunt1 with tty7 for example, from the last part of the address found in dbus-spy

**Comment by pulquero** [comment]
Thanks, done.
