### ISSUE TITLE
Pace Gobel BMS on RS485, Battery Aggregator on RS232 ?

### ISSUE THREAD

**Issue by Starter4711** [pulquero/BatteryAggregator#17]
Hello
would like to ask, it it would be possible to connect Battery Aggregator via RS232, not on RS485 there the Gobel Pace BMS is communicating with the Cerbo automatically. But I would like to see the cell voltages. Thx

**Comment by pulquero** [comment]
Please attach a screenshot of dbus-spy showing the BMS details. Battery aggregator reads directly from dbus so doesnt care about RS232 vs RS485. No reason why it shouldnt work.

**Comment by Starter4711** [comment]
I will do (later), the BA shows the values, same lithe the Cerbo already does if the Gobel is connected to Cerbo.
What I want is more, I would like to see the cell voltages, but this does not depend on BA? If the Can connection does not handover from BMS these values, they arent there and BA does not get these values directly from the Battery, than I need to look for an other addon.

**Comment by pulquero** [comment]
Exactly right.
