### ISSUE TITLE
AB ver. 2.5 not working?

### ISSUE THREAD

**Issue by entropia1ac** [pulquero/BatteryAggregator#19]
Hi, 
I am trying to install BatteryAggregator on Cerbo ver. 3 (3.2) but after installation it is not visible in the device list and in the battery monitor. It is not visible in the logs either.
What could be the reason for this ?
Thank You for your great work!

![SmartSelect_20240217_165133_Termius](https://github.com/pulquero/BatteryAggregator/assets/13286876/212bada7-669d-4d25-84f8-37fa0a3f43eb)
![SmartSelect_20240217_164131_Opera](https://github.com/pulquero/BatteryAggregator/assets/13286876/c38fb62c-c9fe-4dc0-881c-6c7c0c4b7478)
![SmartSelect_20240217_164054_Opera](https://github.com/pulquero/BatteryAggregator/assets/13286876/e9319a05-8e7a-450d-9ece-8bc4a85fc3b8)
![SmartSelect_20240217_164005_Opera](https://github.com/pulquero/BatteryAggregator/assets/13286876/52ce089d-7c91-4f6c-93a4-608bd71c37a9)

**Comment by pulquero** [comment]
Did you check for errors in /var/log/BatteryAggregator/current?

You can also try restarting it with 
svc -d /service/BatteryAggregator
svc -u /service/BatteryAggregator

**Comment by entropia1ac** [comment]
Last login: Sat Feb 17 15:50:57 2024 from 192.168.1.75
root@einstein:~# svc -d /service/BatteryAggregator
svc: warning: unable to chdir to /service/BatteryAggregator: file does not exist
root@einstein:~#

**Comment by pulquero** [comment]
Looks like it didnt install properly, in the package manager, try clicking Download, then Install again.

**Comment by entropia1ac** [comment]
Reinstallation helped.Thank you
