### ISSUE TITLE
  [Question]  SOC to calculate CVL and DCL from the shunt

### ISSUE THREAD

**Issue by entropia1ac** [pulquero/BatteryAggregator#20]
I have 3 virtual batteries from 3 BMSes, each in series with a shunt.

	"virtualBatteries": {
		"com.victronenergy.battery.virtual1": ["com.victronenergy.battery.ttyS7", "com.victronenergy.battery.ttyUSB4"],
		"com.victronenergy.battery.virtual2": ["com.victronenergy.battery.ttyS6", "com.victronenergy.battery.ttyUSB3"],
"com.victronenergy.battery.virtual3": ["com.victronenergy.battery.ttyS5", "com.victronenergy.battery.ttyUSB1"]
	}
}

Is it possible that for the calculation of CCL and DCL the SOC is taken from the shunt and not from the BMS ?

**Comment by pulquero** [comment]
First entry in the array has precedence, so ttyS data will be preferred over ttyUSB. You can swap the order and/or use the more advanced syntax:

	"virtualBatteries": {
		"com.victronenergy.battery.virtual1": {"com.victronenergy.battery.ttyS6": ["/Soc"], "com.victronenergy.battery.ttyUSB0": []},
		"com.victronenergy.battery.virtual2": {"com.victronenergy.battery.ttyS7": ["/Soc"], "com.victronenergy.battery.ttyUSB1": []]
	}

to specify only some dbus paths to take precedence.

**Comment by entropia1ac** [comment]
Great.Thanks

**Comment by entropia1ac** [comment]
BA does not accept a new config.json file :
{
	"virtualBatteries": {
		"com.victronenergy.battery.virtual1": {"com.victronenergy.battery.ttyS7" : ["/Soc"], "com.victronenergy.battery.ttyUSB4":[]},
		"com.victronenergy.battery.virtual2": {"com.victronenergy.battery.ttyS6" : ["/Soc"], "com.victronenergy.battery.ttyUSB2": []},
"com.victronenergy.battery.virtual3": {"com.victronenergy.battery.ttyS5" : ["/Soc"], "com.victronenergy.battery.ttyUSB1": []]
    }
	}
}

![SmartSelect_20240218_154453_Termius](https://github.com/pulquero/BatteryAggregator/assets/13286876/315a69cb-7197-41ad-9a97-adf27aed338a)

**Comment by pulquero** [comment]
Last ] should be a }

**Comment by entropia1ac** [comment]
This option does not work:
{
	"virtualBatteries": {
		"com.victronenergy.battery.virtual1": {"com.victronenergy.battery.ttyS7" : ["/Soc"], "com.victronenergy.battery.ttyUSB4":[]},
		"com.victronenergy.battery.virtual2": {"com.victronenergy.battery.ttyS6" : ["/Soc"], "com.victronenergy.battery.ttyUSB2": []},
"com.victronenergy.battery.virtual3": {"com.victronenergy.battery.ttyS5" : ["/Soc"], "com.victronenergy.battery.ttyUSB1": []}
	}
}

![SmartSelect_20240218_212620_Opera](https://github.com/pulquero/BatteryAggregator/assets/13286876/c07ba805-f3d5-4b8c-a896-be66f5ca4a55)
![SmartSelect_20240218_212504_Termius](https://github.com/pulquero/BatteryAggregator/assets/13286876/39b9b61d-fc17-408e-872b-e6a2b2ad6269)

**Comment by entropia1ac** [comment]
With this file config.json BA sees 4 batteries instead of 3
![SmartSelect_20240219_154448_Opera](https://github.com/pulquero/BatteryAggregator/assets/13286876/aed5eb9d-cb57-4fce-876e-2ec0f2b5bee2)
![SmartSelect_20240219_154327_Opera](https://github.com/pulquero/BatteryAggregator/assets/13286876/ecd3e912-ec2a-4569-9dce-28e9703557b6)
![SmartSelect_20240219_154237_Termius](https://github.com/pulquero/BatteryAggregator/assets/13286876/4e3f3df1-b4bd-4389-9a64-c74377d9a27a)

**Comment by pulquero** [comment]
dbus-spy BA, look at /System/Batteries, it will list the 4 batteries it thinks it has found.
