### ISSUE TITLE
CCL & DCL are not aggregated

### ISSUE THREAD

**Issue by johnboyi** [pulquero/BatteryAggregator#25]
Hi!

I have 2 Systems running, and on both (both 3xMultiplus5000, one system with 2 Basengreen batteries, one with 3 Basengreen batteries) CCL & DCL are not aggregated? Any idea?

![2024-03-06](https://github.com/pulquero/BatteryAggregator/assets/162355139/42fe3556-3fc3-4797-9b5b-4fcafaecdbc4)

dbus-spy
![2024-03-06 (0)](https://github.com/pulquero/BatteryAggregator/assets/162355139/3fed380b-1c59-4fae-a539-b5422220bbaf)

Aggregator:
![2024-03-06 (1)](https://github.com/pulquero/BatteryAggregator/assets/162355139/adcf7458-6734-474a-a60c-a339f8a00728)

1st battery:
![2024-03-06 (2)](https://github.com/pulquero/BatteryAggregator/assets/162355139/290bd1e4-2042-4c7b-bb72-cb54341bf91a)
![2024-03-06 (3)](https://github.com/pulquero/BatteryAggregator/assets/162355139/c8ac9de4-a54e-451f-86b3-8db3fad3ab8f)
![2024-03-06 (5)](https://github.com/pulquero/BatteryAggregator/assets/162355139/ad501756-31d3-42de-ad67-342ac99e1dc0)

**Comment by pulquero** [comment]
Check Io/AllowToCharge on each battery, if it is zero/off then its CCL is ignored (it should probably be taken to be zero, but I can fix that if this is the case).
Also, check the log
cat /var/log/BatteryAggregator/current

**Comment by johnboyi** [comment]
![Screenshot (1)](https://github.com/pulquero/BatteryAggregator/assets/162355139/9650e894-3747-4f7d-8719-b6c47b275a90)
Can this be changed?

here´s the log: 
![Screenshot (2)](https://github.com/pulquero/BatteryAggregator/assets/162355139/b845c4fb-a11e-433a-ba58-2e5d640112a2)

**Comment by pulquero** [comment]
If we are talking about a battery then the logic in dbus-serialbattery is

        self._dbusservice["/Io/AllowToCharge"] = (
            1
            if self.battery.charge_fet
            and self.battery.control_allow_charge
            and self.block_because_disconnect is False
            else 0
        )

It looks like these variables are not supported by lifepower bms hence it is 0. I might try to contact dbus-serialbattery author to try to understand why this is the case.

**Comment by pulquero** [comment]
Has the latest version helped?

**Comment by johnboyi** [comment]
Hi! Yes! It works great! I thank you very very much!!! Robert
-------- Ursprüngliche Nachricht --------Von: pulquero ***@***.***> Datum: 14.03.24  17:31  (GMT+01:00) An: pulquero/BatteryAggregator ***@***.***> Cc: johnboyi ***@***.***>, Author ***@***.***> Betreff: Re: [pulquero/BatteryAggregator] CCL & DCL are not aggregated (Issue
  #25) 
Has the latest version helped?

**Comment by johnboyi** [comment]
Now it works! Thank you!
