### ISSUE TITLE
Current vs. Voltage decimal points display

### ISSUE THREAD

**Issue by seamaster101** [pulquero/BatteryAggregator#32]
@pulquero when using the aggregator with lithium batteries, it will be much more useful to have 3 digits after the decimal point ton the voltage, rather than on the current as it is now. can that be changed/adjusted?
<img width="550" alt="image" src="https://github.com/pulquero/BatteryAggregator/assets/7897023/6a2f5fdc-9230-4158-8085-475d9bf65e27">

**Comment by pulquero** [comment]
Done, v3.0.16.

**Comment by seamaster101** [comment]
thank you, it works great!
