### ISSUE TITLE
After limitation or CCL or DCL (new feature), CVL goes also to 0V. after resuming normal condition, CVL remains 0V

### ISSUE THREAD

**Issue by AlexdeKairos** [pulquero/BatteryAggregator#36]
Testing the new feature of checking FETs state to decide if CCL or DCL must be limited, I found that upon application of both CCL and DCL to 0, CVL goes ALSO to 0v. I think that's a mistake and should not happen. All chargers go to 0V and undervoltage alarm triggers. But after resuming normal condition, the CVL remains 0 even if CCL and DCL goes back to normal. So no charging happens.

**Comment by AlexdeKairos** [comment]
![Screenshot_20240404_133650_VRM](https://github.com/pulquero/BatteryAggregator/assets/157214090/fc3ce7c9-4246-4439-b418-b4ef1a52895e)
![Screenshot_20240404_133706_VRM](https://github.com/pulquero/BatteryAggregator/assets/157214090/af4707ac-9f81-4948-bdd1-0264b2cfbe91)

**Comment by pulquero** [comment]
Pushed fix.

**Comment by AlexdeKairos** [comment]
Seems to be fine on v3.0.20
