### ISSUE TITLE
 low battery

### ISSUE THREAD

**Issue by ondrom111** [pulquero/BatteryAggregator#39]
it says low battery for me. I have 2 batteries, one has 96 percent, the other 100 percent.
![low battery](https://github.com/pulquero/BatteryAggregator/assets/58415073/62f0c1b3-6926-4035-9cfc-b96e6a821a22)
![low battery1](https://github.com/pulquero/BatteryAggregator/assets/58415073/05cc1207-2540-4b58-b54f-4afa081c7ea9)

**Comment by pulquero** [comment]
The low voltage alarm on the aggregator is triggered if it is triggered on any individual battery. Please check the state of the individual batteries.

**Comment by ondrom111** [comment]
all are ok

**Comment by pulquero** [comment]
I've released a new version that has dynamic logging. In dbus-spy, set /LogLevel to DEBUG. The next time it happens please attach the log to this issue.

**Comment by pulquero** [comment]
Is the problem still present in the latest version?
