### ISSUE TITLE
Rename Battery Aggregator and other little Things.

### ISSUE THREAD

**Issue by Scheppo** [pulquero/BatteryAggregator#4]
Hi Pulquero,
the „exclude Battery“ Option is working fine, thx.

Few Things:
1. I Will Change the Battery Aggregator Name in „400AH BAT“ because my battery’s are 280 and 120 Ah.
2. The total AH is not adjustable.
![79643372-7990-4195-9940-5A2CAE4E2F89](https://user-images.githubusercontent.com/130258195/230873269-d8b26f84-5d4f-4e57-a6c8-bec2a0ff4a05.jpeg)
3. There are no Data from the Can Battery here
![D3198D54-6BFB-4350-9ED7-EFFCE6A90A80](https://user-images.githubusercontent.com/130258195/230873636-6855ddb9-a16f-497f-85a4-bf3a6a7032d6.jpeg)

Maybe I have not seen the Options to Change this, sorry.

**Comment by pulquero** [comment]
If you could run dbus-spy and attach screenshots of your battery services then I can check which dbus paths I am missing and add them. Total AH should be computed from the individual battery AHs, but maybe your batteries don't publish that?

**Comment by Scheppo** [comment]
Ok, I can see that the smartshunt don’t send the Capacity, this is strange.

Here are the Infos for the 280ah can Battery:
I need only the Min and Max Cellvoltage here.
![AD1D8BA2-E599-4966-9821-7BFD8D7E7C84](https://user-images.githubusercontent.com/130258195/230904108-7dfd4903-6d5b-4204-a82a-b61892003999.jpeg)

Here ist the 280ah Can Battery over the Smartshunt:
I see no Capacity Info, maybe you can use the Name for the info?
![72DD86F8-2E4D-453A-99BC-80944E1F904E](https://user-images.githubusercontent.com/130258195/230904622-21a1db16-9aba-495c-bc31-74d2e5d9206a.jpeg)

Here ist the 120ah Battery only over Smartshunt:
![4CCD1E41-059F-44E2-99F4-07485ABCF379](https://user-images.githubusercontent.com/130258195/230904927-cbf8665e-eef3-44fc-a34a-ce9b5736f929.jpeg)

I have cut some first entry’s for Alarm to fit in one Picture.
