### ISSUE TITLE
Cerbo GX changed DeviceID every reboot/update

### ISSUE THREAD

**Issue by Scheppo** [pulquero/BatteryAggregator#42]
Hi,

i have installed 2 Batterys:
Bat1 = BMS over BMSCan1 (DeviceID 512) and Shunt over VEBus
Bat2 = BMS over VECan0 (DeviceID 513) and Shunt over USB1

The Problem is when rebooting Cerbo, the DeviceID from Can0 is changing from 513 to 512, but BAT1 have always 512.
Then i must set the ID back to 513 over ssh.
And sometimes also the ShuntUSB1 is switching to USB0 after reboot/Firmwareupdate.

This is no Aggregator fault but maybe you have an Idea to fix this.

thx in advance

**Comment by pulquero** [comment]
There is a file /data/conf/settings.xml that stores persistent Venus settings. You could try looking in that for any relevant references. There is a device instance ID mapping (see https://github.com/victronenergy/venus/wiki/dbus-api#vrm-device-instances) in there. Maybe that is conflicting with the default auto-assignment.
