### ISSUE TITLE
CVL is not aggregated when using CVL_ICONTROLLER_MODE = True

### ISSUE THREAD

**Issue by Albarge** [pulquero/BatteryAggregator#45]
Hi, using v3.0.50 and serialbattery v.1.3.20240417dev I could see Icontroller lower CVL for one battery to 27.2V, but BatteryAggregator stayed at 28V for all three batteries, I'm not sure if this is a serialbattery issue or batteryaggregator. 

This stops the icontroller CVL from working to limit Voltage when a cell goes over max Voltage.

See here: https://github.com/Louisvdw/dbus-serialbattery/pull/882#issuecomment-2064658498

**Comment by pulquero** [comment]
See https://github.com/pulquero/BatteryAggregator/issues/44.

Ideally, what I need to know is "if the batteries have these dbus path values X then the aggregator should do Y". Currently, if any battery is reporting as balancing then the max voltage is used to ensure it can be balanced (at the risk of overvoltage on the other batteries, what else can I do?), otherwise the safer min voltage is used. So the biggest issue is really working out want the best behaviour should be, and if that behaviour will be appropriate for everyone or whether it needs to be configurable.

**Comment by Albarge** [comment]
I don't know the answer to make it work for everyone or easiest way for you to implement, but I would suggest:

 `Info:MaxChargeVoltage` is 27.2V on any battery then aggregator should follow this for all batteries.

Yes it will (temporarily) lower CVL of batteries still balancing, but if a cell(s) are overvoltage it will protect them from overcharge.

If in sbattery config: `CVCM_ENABLE = True` + `LINEAR_LIMITATION_ENABLE = True` then the "CVL reset based on cell voltage diff (linear mode)" can be used to control when to change CVL to Float. 

I think it is a key part of sbattery that it can control CVL if any cells go over voltage, this is a higher risk to accommodate before next making sure all batteries are balanced.

**Comment by pulquero** [comment]
I've pushed a new version that supports a CVL "mode" flag. In the JSON config, add the property
"cvlMode": "min_when_balancing"
See if this achieves what you require. You'll need to restart the BatteryAggregator after modifying the config.

**Comment by Albarge** [comment]
That's great thanks! I've installed and will see how it works tommorow in the sun!

Do I need brackets like this in the json?

`{
	"cvlMode": "min_when_balancing"
}
`

**Comment by Albarge** [comment]
Just looked and saw an old bug? from an earlier version came back with v3.0.51 I only have 3 batteries, but in system it thinks I have 4?

![Screenshot_20240419-231953](https://github.com/pulquero/BatteryAggregator/assets/98849340/bad984fb-1526-4ad1-950a-0bf4135829a7)

**Comment by pulquero** [comment]
> That's great thanks! I've installed and will see how it works tommorow in the sun!
> 
> I didn't put brackets on this property, but does It need brackets like this in the json?
> 
> `{ "cvlMode": "min_when_balancing" } `

Yes, if not already present.

**Comment by pulquero** [comment]
> Just looked and saw an old bug? from an earlier version came back with v3.0.51 I only have 3 batteries, but in system and dbus batteryaggregator thinks I have 4?
> 
> ![Screenshot_20240419-231953](https://private-user-images.githubusercontent.com/98849340/324129853-bad984fb-1526-4ad1-950a-0bf4135829a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NjY4MTUsIm5iZiI6MTcxMzU2NjUxNSwicGF0aCI6Ii85ODg0OTM0MC8zMjQxMjk4NTMtYmFkOTg0ZmItMTUyNi00YWQxLTk1MGEtMGJmNDEzNTgyOWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDIyNDE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzY2FjN2Q1NjI5ODcxMWI1YmViZDc0NjVmODE2YWUyZGZhZWU1YzY1NDcyYWM5NTg0ODQ3N2Q5MTEwMGE3NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K7oeBWWrWmO6Hfyfy8zbX9-fncXnom--bfduK2DR4Bw)

If you check /System/Batteries you can see the names of the 4  batteries to see what it thinks the fourth one is.

**Comment by Albarge** [comment]
I think it is adding the SmartShunt again (ttyS7), is one of these the system/batteries location you mean on dbus-spy?

![system](https://github.com/pulquero/BatteryAggregator/assets/98849340/9dd36a26-1816-448b-b2ec-5501b736b163)

![batteries](https://github.com/pulquero/BatteryAggregator/assets/98849340/28b89b58-e399-4404-99b0-0e34574b9bec)

I thought it was excluded with the "primaryServices" property but it wasn't so I added "excluded.." but aggregator is still seeing 4 batteries?

![excluded](https://github.com/pulquero/BatteryAggregator/assets/98849340/921b4e98-538d-430f-a668-5f0674b8e472)

**Comment by Albarge** [comment]
So it looks like it doesn't like my json:

![log](https://github.com/pulquero/BatteryAggregator/assets/98849340/f23cbcc7-10d5-4a32-9c44-01897d964d60)


This is the latest config it ignored also;

![json](https://github.com/pulquero/BatteryAggregator/assets/98849340/cb6fa23b-7667-4132-a027-49707baf51cb)

Did I format incorrectly, or could this be related to your solution for this? 

https://github.com/pulquero/BatteryAggregator/issues/33#issue-2206198341

**Comment by pulquero** [comment]
Your json is incorrect, it should be of the form
{
"KEY1": "value",
"Key2": "value",
"Key3": "value"
}

**Comment by Albarge** [comment]
Like this?

```
{ 
 "primaryServices": {"com.victronenergy.battery.ttyS7": ["/Soc"]

 "cvlMode": "min_when_balancing" 
}
```

**Comment by pulquero** [comment]
{ 
 "primaryServices": {"com.victronenergy.battery.ttyS7": ["/Soc"] },

 "cvlMode": "min_when_balancing" 
}

**Comment by Albarge** [comment]
That worked! Only 3 batteries showing and no JSON warning. 

I really appreciate your work on this driver and the support, Thankyou. : )

**Comment by Albarge** [comment]
The update works. Thanks.

Using the P-CONTROLLER in Serial Battery:

I've been watching the CVL gently kick in every so often to Limit the Max Voltage for all batteries which keeps the runner cells in one battery from going too high, until the cell voltage differentials reduce closer to the target Voltage. This also makes the final stage of absorption charging smoother. So it seems to really help with unbalanced, or runner cells jumping ahead. :)
