### ISSUE TITLE
V1.8 not working

### ISSUE THREAD

**Issue by Scheppo** [pulquero/BatteryAggregator#5]
First of all thx for your fast programming.

when I add the „capacity“: 400 to config.json then the System don’t work.
SSH connection is very slow and I can’t change the config.json anymore.
Reboot don’t help

**Comment by Scheppo** [comment]
Ok, I have deleted the config.json file. Now the ssh connection is stable again.
I have uninstalled BatteryAggregator befor but it was hard to come to the ssh console.

**Comment by pulquero** [comment]
The error is your json file is invalid, missing a comma separating the two entries. I suspect it got stuck in a loop trying to continually restart the service. Added a check to safely ignore invalid files. Note you can check the log for errors with
`cat /var/log/BatteryAggregator/current`

**Comment by Scheppo** [comment]
Sorry iam Beginner in Linux so i don’t know the right Syntax in json file.
It works now, but the Detail Page is empty:
![64493CB7-F7DB-4F9B-BEC6-855F63888C5B](https://user-images.githubusercontent.com/130258195/231002798-ad785b00-a640-4036-8213-5aaf158ff268.jpeg)

**Comment by pulquero** [comment]
Log looks ok. To confirm, the details page works if you don't exclude the can battery? So, I think you need to exclude the smart shunt for the can battery instead of the can battery.

**Comment by pulquero** [comment]
Ah, I see, so really want you need is a "virtual battery" that merges the shunt and can data. Then aggregate that with the other shunt?

**Comment by Scheppo** [comment]
Yes I need only MinCellVolt and MaxCellVolt from Can Battery in Batteryaggregator.

My System is follow:
One 120Ah Battery with Smartshunt
One 280Ah Battery with Smartshunt and also Can connected.

**Comment by pulquero** [comment]
I've now added virtual battery support. Note, there is an issue with stopping the service - you'll need to manually kill any child processes.
