### ISSUE TITLE
exclude service

### ISSUE THREAD

**Issue by rolandlueders** [pulquero/BatteryAggregator#55]
v3.0.63

Three Banks 24V300Ah/JK-BMSes parallel

Hardware: Cerbo/RPi??? Rpi 4

Setup: DVCC? yes

I want to exclude the Smartshunt becaue the Current in Batteryaggregator is twice of the Shunt and he count of batteries is 4.
When i look to dbus-spy i find the smartshunt as Battery:
com.victronenergy.battery.ttyUSB2
So i created a         /data/setupOptions/BatteryAggregator/config.json  
There i added   "excludedServices": ["com.victronenergy.battery.ttyUSB2"] and restarted the service. I coldnt see any change. When i rebooted the RPI, the Smartshunt was now com.victronenergy.battery.ttyUSB4.

**Comment by pulquero** [comment]
Please check the log for any errors. Please confirm the contents of you file is like 
```
{
	"excludedServices": ["com.victronenergy.battery.ttyS1"]
}
```

To address the service name changing, can you verify the DeviceInstance and/or CustomName also change.
