### ISSUE TITLE
select the highest CVL  in Multible Batterie Systems

### ISSUE THREAD

**Issue by rolandlueders** [pulquero/BatteryAggregator#56]
RPi 4

Setup: DVCC? yes

I have three banks 24V/300Ah with JK-BMSes in parallel.
because i want to reduce the Voltage as much as possible, the Batteryaggregator should read the highest CVL of the Batteries so that all Batteries can finisch absobtion or balancing or Load_to_SOC_reset. Now Batteryaggregator takes the lowest CVL of the Batteries. It is possible to add a switch for that?

**Comment by rolandlueders** [comment]
My english is bad. Therfore i asked a friend for better text:
I am currently using a setup with three 24V/300Ah battery banks equipped with JK-BMSes, all connected in parallel. My primary goal is to ensure that all batteries can complete absorption, balancing, or reach the Load_to_SOC_reset state effectively. Currently, the Batteryaggregator selects the lowest CVL (Charge Voltage Limit) from the batteries, which might not be optimal for my system.

Could it be possible to introduce a switch or setting in the Batteryaggregator that allows for the selection of the highest CVL instead? This change would help in making sure all batteries are adequately managed during their charge cycles.

**Comment by pulquero** [comment]
It should use the highest CVL when balancing (and the lowest otherwise). Do they not reach the balancing stage?

**Comment by rolandlueders** [comment]
Thanks for your reaction. In my case it would better if always th highest CVL is in use

**Comment by pulquero** [comment]
I've added a max_always CVL mode:

"cvlMode": "max_always"
