### ISSUE TITLE
unsupported operand type(s) for -: 'float' and 'NoneType'

### ISSUE THREAD

**Issue by erhankeseli** [pulquero/BatteryAggregator#63]
Please include system details:

Hardware: Cerbo

Setup: 4 Batteries, all same type but different name. When the usage is high (4000Watts) i get an exception.

com.victronenergy.battery.aggregator                                                 Battery Aggregator
com.victronenergy.battery.socketcan_can0                                              Pylontech battery
com.victronenergy.battery.socketcan_can1                                               BMS-CAN

CRITICAL:ve_utils:exit_on_error: there was an exception. Printing stacktrace will be tried and then exit
@40000000668ea5b62e852824 Traceback (most recent call last):
@40000000668ea5b62e852ff4   File "/data/BatteryAggregator/ext/ve_utils.py", line 22, in exit_on_error
@40000000668ea5b62e853f94     return func(*args, **kwargs)
@40000000668ea5b62e854764   File "/data/BatteryAggregator/ext/dbusmonitor.py", line 345, in _execute_value_changes
@40000000668ea5b62e85531c     self.valueChangedCallback(serviceName, objectPath,
@40000000668ea5b62e8825c4   File "/data/BatteryAggregator/battery_service.py", line 509, in _service_value_changed
@40000000668ea5b62e88394c     self._battery_value_changed(dbusServiceName, dbusPath, options, changes, deviceInstance)
@40000000668ea5b62e8848ec   File "/data/BatteryAggregator/battery_service.py", line 535, in _battery_value_changed
@40000000668ea5b62e8854a4     self._add_vi_sample(dbusServiceName, voltage, current)
@40000000668ea5b62e8a19c4   File "/data/BatteryAggregator/battery_service.py", line 469, in _add_vi_sample
@40000000668ea5b62e8a2d4c     updated, changed = irdata.append_sample(voltage, current)
@40000000668ea5b62e8a3904   File "/data/BatteryAggregator/battery_service.py", line 336, in append_sample
@40000000668ea5b62e8a48a4     has_changed = abs(ir - self.value) > math.hypot(err, self.err)
@40000000668ea5b62e8a545c TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

I get an exception and

**Comment by pulquero** [comment]
Fixed in v3.0.70.
