### ISSUE TITLE
custom charge curve

### ISSUE THREAD

**Issue by adcrafter27** [pulquero/BatteryAggregator#66]
Hello, as already written in another post 
https://github.com/pulquero/BatteryAggregator/issues/65#issuecomment-2297104345

I would like to have my own charging curve
because I use different BMS and can't adjust them all

I have 2x JKBMS 15S and 6x Pylontech 15S

e.g 
50Volts -> 100A 
51Volt -> 70A 
52Volt -> 30A 
52.5 volts ->0A (in my case 100% full)

This way I can charge my batteries more slowly when they get full

**Comment by pulquero** [comment]
I've been given this some thought. I'm considering creating a separate battery proxy/wrapper that can add custom charging to any battery (aggregator, pylontech, whatever). In fact, I already have a BatteryProxy project, which sort of emulates a BMS. I'm sort of undecided how best to go about this. I'm sort of reluctant to add charging functionality to the aggregator itself as that will complicate the code.

Here is a hypothetical question, if all your batteries were JKBMS, would this be an issue? It seems it wouldnt be, which suggests the real issue is augmenting the pylontech dbus service.

**Comment by adcrafter27** [comment]
If all batteries were JK BMS I wouldn't have any problems because I can control everything via dbus-serialbattery.
but the Pylontech batteries are directly connected to the venus OS

**Comment by pulquero** [comment]
First stab at this is ready for testing in the main branch. Example config:
```
  "virtualBatteries": {
     "com.victronenergy.battery.better_pylon": ["class:hooks.CustomChargingHook", "com.victronenergy.battery.origional_pylontech _battery"]
  },
  "classes": {
     "hooks.CustomChargingHook": {
           "ccls": {
                  "50": 100,
                  "51": 70,
                  "52": 30,
                  "52.5": 0
           }
      }
  }

**Comment by adcrafter27** [comment]
> First stab at this is ready for testing in the main branch. Example config:
> 
> ```
>   "virtualBatteries": {
>      "com.victronenergy.battery.better_pylon": ["class:hooks.CustomChargingHook", "com.victronenergy.battery.origional_pylontech _battery"]
>   },
>   "classes": {
>      "hooks.CustomChargingHook": {
>            "ccls": {
>                   "50": 100,
>                   "51": 70,
>                   "52": 30,
>                   "52.5": 0
>            }
>       }
>   }
> ```


Thanks, I tested it. But there are errors. No virtual battery is created either.
The Pylontech battery is also excluded from the aggregator.

I have not excluded the shunt as a test (ttyUSB1)

Cerbo Firmware: v3.42
BatteryAggregator v3.3 main

Have I done something wrong?

![2024-09-20 14_00_53-H__OneDrive_Bibliotheken_PC Daniel_Dokumente_MobaXterm_slash_daniel_pcdaniel_mx8](https://github.com/user-attachments/assets/b389345d-bc6b-40e4-a5dd-f10af2d1e3d3)
![2024-09-20 13_58_02-Cerbo-Victron-61](https://github.com/user-attachments/assets/12ce1449-d34c-4fee-b4b6-14441f8f1b11)
![2024-09-20 14_01_14-Cerbo-Victron-61](https://github.com/user-attachments/assets/80bcd850-2c94-44e0-b58a-24072eda1756)
![2024-09-20 14_06_43-](https://github.com/user-attachments/assets/32359b38-7bde-48d2-b580-3e87e44d2810)

**Comment by pulquero** [comment]
I've been a bit slow to get back to this, but you should find that it works now in the latest version.

**Comment by adcrafter27** [comment]
> I've been a bit slow to get back to this, but you should find that it works now in the latest version.



Thanks for your great work, that's no problem, I have time.
I have now tested the “latest” version v3.5

a virtual battery is created. but it is a one-to-one copy of Pylontech without the adjusted ccls values

Pylontech: 
CLV 53.2V
CCL198
DCL 198
The virtual battery has the same values




![image](https://github.com/user-attachments/assets/671ec134-6e78-4580-9f69-0265635fd480)
![image](https://github.com/user-attachments/assets/546a598b-e6b8-45d9-9232-7d1593ef5d25)
![image](https://github.com/user-attachments/assets/675b9342-d063-430b-9747-05fabff7b5b4)

**Comment by pulquero** [comment]
That dbus.String shouldnt be in there, try v3.7.

**Comment by adcrafter27** [comment]
> That dbus.String shouldnt be in there, try v3.7.


Thanks, it works perfectly now.
Thank you for implementing this for me.
