### ISSUE TITLE
Agregator logs zero until first battery comes online.  

### ISSUE THREAD

**Issue by rldoose** [pulquero/BatteryAggregator#67]
Please include system details:
Three JBD serial batteries 

Hardware: Cerbo/RPi???
I have run it on both Cerbo and RPi with same results

Setup: DVCC?
NA

Please provide output from dbus-spy.
NA

Please attach any relevant logs. Log location is `/var/log/BatteryAggregator/current`.
NA

The zero volts is annoying, and just plain wrong.  Agregator should not report until there is something to report. This wacks the scale of my graphs which must now go from zero to 14.2 instead of about 12 to 14.2.  

<img width="420" alt="Screenshot 2024-08-24 at 21 00 09" src="https://github.com/user-attachments/assets/94fe5bdf-470d-402b-89bf-e8285febc4c9">
<img width="315" alt="Screenshot 2024-08-24 at 20 59 40" src="https://github.com/user-attachments/assets/f697f5c2-4149-482b-ac4f-ceaa552d69f2">

**Comment by pulquero** [comment]
Wow, "just plain wrong", harsh. The only thing that is plain wrong is that statement. The aggregator is a battery, a battery not reporting a voltage can cause issues. What I can do is probably delay dbus registration until a valid voltage is available.

**Comment by rldoose** [comment]
You are right, I was unnecessarily harsh.  Especially directed at someone providing something for free,  Please accept my apologies.
