### ISSUE TITLE
Time To Go

### ISSUE THREAD

**Issue by wetty** [pulquero/BatteryAggregator#69]
I have two batteries in parallel connected.
The first one shows a time to go from 12:32h
The second one shows 14:02h

BatteryAggregator shows 13:40h for the overall time to go.

In my understanding the time to go should not be the average of both batteries, but more the time of the battery that take the longest.

BatteryAggregator Version 3.0.82
Venus OS Version 3.50-20
Running on a Raspberry 3+

**Comment by pulquero** [comment]
My reasoning for using the average is that the load on the second battery will start to increase as the first battery empties and therefore will end up being less than the 2nd battery TTG (but more than the 1st). Ultimately they both have to empty at the same rate (voltage is same for both), and the load (current) is distributed accordingly (as the internal resistances change based on SoC).
