### ISSUE TITLE
CVL values are not summarized

### ISSUE THREAD

**Issue by Micha854** [pulquero/BatteryAggregator#7]
Hello,

i connected a pylontech via can and connected a DIY battery pack to the "dbus-serialbattery driver" from louis.

CVL pylontech = 53.2V
CVL serial battery = 50.25V

the "BatteryAggregator" shows me CVL = 50.25V

shouldn't that be 51.725V?

can we solve the problem?

**Comment by pulquero** [comment]
Please provide dbus-spy screenshots of the two. I need to confirm they are using the same dbus paths.

**Comment by pulquero** [comment]
Closing as no response received.
