### ISSUE TITLE
Constant crash using 3.2 version - module not found

### ISSUE THREAD

**Issue by endurance1968** [pulquero/BatteryAggregator#71]
Just installed 3.2 version but it is constantly crashing due to module not found

Hardware: Cerbo 3.41
BA 3.2  

Traceback (most recent call last):
@4000000066e7bc04363d0474   File "/data/BatteryAggregator/battery_service.py", line 23, in <module>
@4000000066e7bc04363d1414     from pydoc import locate

than I tried to go back to tag 3.0.81 but the result is
@4000000066e7bfea1426c294 INFO:main:Starting...
@4000000066e7bfea158abb7c Traceback (most recent call last):
@4000000066e7bfea158ae28c   File "/data/BatteryAggregator/battery_service.py", line 966, in <module>
@4000000066e7bfea158aee44     main()
@4000000066e7bfea158af22c   File "/data/BatteryAggregator/battery_service.py", line 938, in main
@4000000066e7bfea158afde4     batteryAggr = BatteryAggregatorService(dbusConnection(), DEFAULT_SERVICE_NAME, config)
@4000000066e7bfea158b0d84   File "/data/BatteryAggregator/battery_service.py", line 390, in __init__
@4000000066e7bfea158d18f4     self.monitor = DbusMonitor(
@4000000066e7bfea158d2894 TypeError: __init__() got an unexpected keyword argument 'excludedServiceNames'

so currently the aggregator is not running at all - any tipps?

**Comment by endurance1968** [comment]
Hmm - i installed the packes needed for config check and reinstalled version 3.2 and now it works again.
NMot sure if the error was fixed by installing the extra packages or by reinstalling v3.2

**Comment by SlapJackNpNp** [comment]
I have two systems running battery aggregator and the modul is not found on either. What exactly did you do to fix this, which packages are you talkin about?

**Comment by SlapJackNpNp** [comment]
I uninstalled 3.2, rebooted the cerbo and installed it again but it still doesn't work. The Pacakges also don't seem to be installable via package manager? This is unfortunate since i acces the systems remotely.

**Comment by pulquero** [comment]
Try downloading and installing again via package manager. It seems it didnt download a newer version of the VELib library. Also look in the log for a line "++ Install Python library velib_python" and there were no errors.

**Comment by erhankeseli** [comment]
I get another error:
Traceback (most recent call last):
@4000000066e7f6862cf97f14   File "/data/BatteryAggregator/battery_service.py", line 23, in <module>
@4000000066e7f6862cf98acc     from pydoc import locate
@4000000066e7f6862cf9929c ModuleNotFoundError: No module named 'pydoc'

**Comment by pulquero** [comment]
> I get another error: Traceback (most recent call last): @4000000066e7f6862cf97f14 File "/data/BatteryAggregator/battery_service.py", line 23, in @4000000066e7f6862cf98acc from pydoc import locate @4000000066e7f6862cf9929c ModuleNotFoundError: No module named 'pydoc'

what version of venus are you running?

**Comment by erhankeseli** [comment]
3.10-22

**Comment by SlapJackNpNp** [comment]
Running bash /data/BatteryAggregator/check_config.sh and installing the two packages helped to get it running again. But if possible it would be great if the files would be included in the packagemaanger files

**Comment by pulquero** [comment]
> 3.10-22

Try upgrading to 3.42.

**Comment by Feil1** [comment]
i had the same problem, i also uninstalled, restartet, installed new nothing helped,
but bash /data/BatteryAggregator/check_config.sh    has helped and now its working again.

**Comment by SlapJackNpNp** [comment]
I updated my cerbo to the latest v3.50~22 and the Aggregator stopped again. To get it working, i had to run the bash /data/BatteryAggregator/check_config.sh command again and install the packages to get it running. uninstalling and redownloading with package manager didn't help. Maybe it is important to notice that i don't use the venus-os large image but the regular one?

**Comment by pulquero** [comment]
Ah maybe. I only test on large. Please paste log with install output.

**Comment by SlapJackNpNp** [comment]
Uh sorry, but could you quickly explain what to put into the ssh to get the logs you need and in which condition? Atm i got everything running again. Can i still get the log you need?

**Comment by PatrickGoettsch** [comment]
If you have root access via ssh
You just copy and paste this

bash /data/BatteryAggregator/check_config.sh

**Comment by endurance1968** [comment]
just upgraded to latest Venus release - some issue. On the normal venus (not large)version you definitely have to install extra packages.
Simplest is to run as suggest the config checker - but this can only be a workaround.

**Comment by SlapJackNpNp** [comment]
![grafik](https://github.com/user-attachments/assets/ac006d48-fe48-47b8-aba2-06c15c2abd05)
This is what i got with cat /var/log/BatteryAggregator/current
The Battery Aggregator is stopping every time i do a software update and only works after the config check command. I only use the regular venus-os and not the large one.

**Comment by pulquero** [comment]
Ahhh, I know what needs to be done now...
