### ISSUE TITLE
CCL 30A and Battery charge is 88A

### ISSUE THREAD

**Issue by Rubens974** [pulquero/BatteryAggregator#76]
Please include system details:

Hardware: RPi

Setup: DVCC
![image](https://github.com/user-attachments/assets/594de1b1-894a-42b6-bf95-7b8d856b336c)

config
{
"logLevel": "DEBUG",
"capacity": 500,
"currentRatioMethod": "capacity",
"cvlMode": "min_when_balancing"
}

Hi, 
Can you tell me if this is normal?
 
![image](https://github.com/user-attachments/assets/61d8a43c-55d4-407d-be7b-25aa11ac2793)
![image](https://github.com/user-attachments/assets/a11d5edc-12bb-4241-b394-1fc2ec508b94)

Best regards

**Comment by pulquero** [comment]
The current logic is if "limit charge current" is off then the ccl setting is ignored and it is assumed the bms provides the ccl.

**Comment by Rubens974** [comment]
Thank you 
So I must activate "limit charge current" in DVCC menue
I will try this.

Regards
