### ISSUE TITLE
two virtual batteries with two custom CCL

### ISSUE THREAD

**Issue by Rubens974** [pulquero/BatteryAggregator#78]
Hello,
Is it possible to have two independant custom CCL, when two virtual batteries installed?

"virtualBatteries": {
     "com.victronenergy.battery.better_pylon": 
        ["class:hooks.CustomChargingHook", "com.victronenergy.battery.origional_pylontech _battery"],
     "com.victronenergy.battery.better_liontron": 
         ["class:hooks.CustomChargingHook",com.victronenergy.battery.origional_liontron_battery"]
  },
  "classes": {
     "hooks.CustomChargingHook": {
           "ccls": {
                  "50": 100,
                  "51": 70,
                  "52": 30,
                  "52.5": 0
           }
      }
  }

Best regards

**Comment by pulquero** [comment]
Now, you can. You just need to append a "hashtag" to differentiate, eg "class:hooks.CustomChargingHook#batt1" and then "hooks.CustomChargingHook#batt1" for the ccl config.
