### ISSUE TITLE
Bug: Smart Shunt is detected as Battery

### ISSUE THREAD

**Issue by WaldemarFech** [pulquero/BatteryAggregator#8]
I've got 2 Batteries and one SmartShunt - so the BatteryAggregator detects 3 Batteries.

One Battery is currently not charging- and discharging. So the values of the other Battery is doubled, because of the Shunt.
![image](https://user-images.githubusercontent.com/11853501/236859660-80c89566-02f4-478b-b271-2c49db1c7afa.png)

**Comment by WaldemarFech** [comment]
My Fault: RTFM
sorry!

Configuration
Optionally create the file /data/setupOptions/BatteryAggregator/config.json.

To exclude the battery service com.victronenergy.battery.shunt1, add:

{
	"excludedServices": ["com.victronenergy.battery.shunt1"]
}

**Comment by pulquero** [comment]
The other option is to create a virtual battery from the merged combination of the shunt + battery it is monitoring.

**Comment by WaldemarFech** [comment]
> My Fault: RTFM sorry!
> 
> Configuration Optionally create the file /data/setupOptions/BatteryAggregator/config.json.
> 
> To exclude the battery service com.victronenergy.battery.shunt1, add:
> 
> { "excludedServices": ["com.victronenergy.battery.shunt1"] }

In my case it is a VE-direct Shunt. So i had to insert:

com.victronenergy.battery.ttyS7

It would be great if we could choose which battery to aggregate or to exclude in the Remote-Console
