### ISSUE TITLE
Not an issue, but I'm to stupid. - Maybe others, too. 

### ISSUE THREAD

**Issue by wattbaron** [pulquero/BatteryAggregator#81]
Thank You for your great work!
Im Using your aggregator now since 2 weeks, and had no problem.

Today i want to integrate current and SOC from Shunt. The helpfull json configurator does the job very well.

I tried several hours, till I made it work.

The problem was, I flled in the shunt by  Excluded Services + by Primary Services.
Would be nice if you write a sentence like:

If a device is excluded, its not available by Primary Services.
Devices, which are listed by Primary Services, are automatically excluded from aggregation.

Many Thanks again for your work.

Wattbaron

**Comment by pulquero** [comment]
Doc improved.
