### ISSUE TITLE
install failed unknown error 127 Raspberry Error after update.

### ISSUE THREAD

**Issue by BATMAR123** [pulquero/BatteryAggregator#84]
Hallo, 
After a CDSystemAggregator update, the software hangs and cannot be installed or uninstalled. See pictures. Can someone please give me a command to uninstall it with PuTTY. 
Thanks

![Screenshot 2024-12-29 at 22-36-02 Remote Console on LAN](https://github.com/user-attachments/assets/1860de37-163f-4206-9b32-5ffd0b8b6c47)

![Screenshot 2024-12-29 at 22-26-30 Remote Console on LAN](https://github.com/user-attachments/assets/880ad43b-541b-45c2-bafc-9d588aaf7ad0)

**Comment by pulquero** [comment]
Do you have SetupHelper installed correctly?

**Comment by BATMAR123** [comment]
![Screenshot 2024-12-29 at 23-20-52 Remote Console on LAN](https://github.com/user-attachments/assets/8f60a9bd-94f8-4547-a576-f3fb1afc4b32)


I think so

**Comment by pulquero** [comment]
You should be able to uninstall using setuphelper then. You could also try installing DCAggregatorService and BatteryAggregator again in case something didnt download properly.

**Comment by catweazle0172** [comment]
I have the same issue here as well.
Seems to be that the new SetupHelper is not compatible anymore.
The location of the following directory is changed in SetupHelper: /data/SetupHelper/CommonResources to /data/SetupHelper/HelperResources/CommonResources
But after the change of the location other errors occurs.

**Comment by pulquero** [comment]
I've pushed fixes to all my packages, try now.

**Comment by BATMAR123** [comment]
Thanks for fixing. It works again.
